# Generated by Django 3.0.4 on 2020-03-17 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_account_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
